### ISSUE TITLE
[megascan-assembler] load recipes from data files instead of hardcoding them

### ISSUE THREAD

**Issue by barbeque** [joymachinegames/joymachine-public#2]
The general format of each 'recipe' is something like: "Take a bunch of files and bundle each one into a varying number of channels."

Examples we have:
 * `_n.tga` is produced from `*Normal.jpg` (mandatory) (one to many)
 * `_a_d.tga` is produced from `*Albedo.jpg` mapped over RGB and `*Displacement.jpg` mapped over A (one to many + one to one)
 * `_m_r_c_ao.tga` is produced from `*Metallic.jpg` (optional), `*Roughness.jpg`, `*Cavity.jpg`, `*AO.jpg` mapped to R, G, B, A respectively (one to one)

We can generically implement one-to-one and one-to-many recipes and build a parser that reads an input datafile for any arbitrary demands on this system. That way, we can support new bundle formats as they are required (I think there is at least one new one that Trent needs that this one does not currently support, though it is quite rare).

**Comment by trentpolack** [comment]
Closing: [https://github.com/joymachinegames/joymachine-public/commit/4bd83023d8df8827ffb96ec9dd6b1ffbe7c7b20d](https://github.com/joymachinegames/joymachine-public/commit/4bd83023d8df8827ffb96ec9dd6b1ffbe7c7b20d)
