### ISSUE TITLE
[jmkernels] No output from command-line. 

### ISSUE THREAD

**Issue by trentpolack** [joymachinegames/joymachine-public#4]
Command: `.\jmkernels.exe sphere -o .\kernel.exr -c 25 -w 512 -r 384 -p 4`

Also no warning/error given. Should be verbose and spit out that a file was created, regardless.

**Comment by barbeque** [comment]
Fixed in ab1763c. Problem was that I never stored the output path we determined from parsing the command line args, so when we checked if that output path was null, it always was, so we bailed on it.
