### ISSUE TITLE
[jmkernels] Add generator type information to the help menu.

### ISSUE THREAD

**Issue by trentpolack** [joymachinegames/joymachine-public#5]
(Currently doesn't explicitly say `sphere` is necessary).

**Comment by barbeque** [comment]
Right now, until we add another verb, `sphere` is automatic. There doesn't seem to be a way until we add a second verb to make it tell us about the verb information. Might need to hold off on this one until the next kind of generator is around.

**Comment by trentpolack** [comment]
The only other (incredibly small) thing is that `-h` isn't a valid option, only `--help`. 

Still results in the help being shown, but I'd like it as a shortcut either way.

**Comment by trentpolack** [comment]
These... Aren't working like I'd imagine they should be. I'm going to ping someone at Epic today or tomorrow to see how to best generate a solid kernel template.

**Comment by barbeque** [comment]
Hear anything back?

**Comment by trentpolack** [comment]
Yeah, kind of. I was hoping for more of a technical discussion, but it entailed watching a Twitch stream so I obviously didn't do it.

In general: the ones we've been doing are wayyyyyyy too big. We need to be talking like maybe 16-32px out of 256px images. I'd like to try it out, but we're not using the FFT bloom right now anyway, so I'm not in a yank.

**Comment by trentpolack** [comment]
I'm going to remove this tool; the actual FFT bloom texture generation isn't trivial to handle (it's actually a kernel applied to a fullscreen image effect).
