### ISSUE TITLE
[megascan-assembler] Fix the albedo/transparency/normal map handling.

### ISSUE THREAD

**Issue by trentpolack** [joymachinegames/joymachine-public#9]
All RGB images were being output as single-channel files, so I think I fixed that, but it was pretty hacky since I've used Python _never_ before.

Also it'd be lovely if, once the ZIP is created and saved and all good, that all the artifacts that were just zipped up were removed.

**Comment by trentpolack** [comment]
Some additional changes we need to make:
- Figure out a way to handle differing types of asset types (not meshes, because those require manual work), but, say: atlases vs. surfaces. 
  - Atlases: albedo, normal, translucency (subsurface scattering), opacity mask, and roughness. Typically not AO and never metallic (so far, anyway, but it's mostly all been foliage). This resulted in me outputting: albedo, translucency (which is RGB too), normal, and mask/roughness/unfilled.
  - Standard materials: we have these pretty well handled.

Next is the naming; often times the folders/zips themselves are well-named (like I just did `Plant_Annuals_oijol2_4K_atlas_ms`) but the files are named `oijol_4K`. So, we need to ensure that we're using the most verbose name of the two (it's _usually_ the folder, but I can't say that with all certainty). And then all lowercase, etc.

**Comment by barbeque** [comment]
Pretty sure I've got the main thrust of this issue done. I added a new rule type, `rgb`, which just thunks the existing `do_saveas` code on the requested texture.

Unsure about what to do with surfaces and naming; can we break those out into separate issues so I can close out this one?

**Comment by barbeque** [comment]
Closing, Trent will make new tickets for the others.
